base_url = "https://lemosjose.github.io"

compile_sass = true

build_search_index = false

theme = "block"

[extra]
[extra.intro]
heading = "Procurando Lemos"
subheading = "Delírios, Thoughts y Tonterias"
avatar_url = "/images/artwork.jpg"
