on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: setup_npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: build_theme_css
        run: |
          cd themes/block
          npm ci
          npm run css:build

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}